### ISSUE TITLE
unicode char length is wrong..

### ISSUE THREAD

**Issue by kksworks** [darkriszty/MarkdownTablePrettify-VSCodeExt#31] opened 2020-05-08 04:50 UTC
Alignment is not possible for double-byte characters like Korean. The length of the string seems to be wrong.
![img_607](https://user-images.githubusercontent.com/8262405/81371426-c2c05b80-9132-11ea-85e3-84fd5968fd4d.png)

**Comment by darkriszty** [comment] 2020-05-10 08:45
Hi and thanks for reporting. 
Unfortunately, the current implementation of CJK support is not good enough. As this is a known issue, I will close this one as duplicate and reference it in the other one.
 
Duplicate of #4

**Closed by darkriszty** 2020-05-10 08:45 UTC
