### ISSUE TITLE
Paste doesn't work in MD files

### ISSUE THREAD

**Issue by yaagma** [darkriszty/MarkdownTablePrettify-VSCodeExt#42] opened 2020-10-15 09:25 UTC
Steps to reproduce this bug:
1. Copy some text (Ctrl+C).
1. Write anything in a line and press Ctrl+V (paste).

Before the text is pasted, all the previous characters in that line are also **duplicated**.

Thanks
Raúl

**Comment by darkriszty** [comment] 2020-10-15 11:05
Hi @yaagma,

First of all, thanks for trying out the extension and taking the time to report an issue!

This extension is not doing anything during copy-paste operations. Formatting is only applied during an operation explicitly triggered by the user: *Format document*, *Format selection*, *Prettify markdown tables* or any keyboard shortcuts associated with these. The default keyboard shortcut for the built-in *Format document* is SHIFT + ALT + F, while for the custom *Prettify markdown tables* it is CTRL + ALT + M.

I am not able to reproduce the problem you described. 
These are the steps I took:
- Open an existing MD file. Tried it with different markdown files plus also both with & without tables inside.
- Copy text from a different file (CTRL + C & right click -> copy). Tried copying single line texts, multi line texts and also tables.
- Paste text in the MD file. Tried both with CTRL + V shortcut and right click -> paste. Also tried to paste it on an empty line, line with text and line with table.

**Result**: the text is being pasted normally every time, without any duplication.

I think either some keyboard shortucts that you have configured or another extension is interfering. 
Could you please check your keyboard shortcuts and retry this will all other extensions disabled? Let me know if the issue still persists afterwards, and if yes, please provide more details on how I could reproduce it (for instance: VS Code version, extension version, OS platform, more detailed steps and concrete file and clipboard contents).

Thanks!

**Comment by yaagma** [comment] 2020-10-19 07:19
Thank you for responding so quickly.
I need a few days, but I will try to create a minimal environment with portable VSC and try to reproduce the error in a isolated environment.

Thanks for all.

**Comment by danmactough** [comment] 2020-11-03 14:20
+1 on this report. With this extension enabled, every paste operation (in a document in any language, not just Markdown) appears to paste the entire line of the selection that was copied rather only the selection. Disabling or removing this extension fixes this behavior.

**Comment by darkriszty** [comment] 2020-11-03 16:14
Hi @danmactough, thanks for your input. This is pretty bizarre as I'm still not able to reproduce it and I also cannot think of a reason behind this behavior.

![paste](https://user-images.githubusercontent.com/2570279/98011175-cf7aef00-1df7-11eb-9da4-3f9fbca6b9a8.gif)

Could you please provide more details? For instance: 
- OS platform.
- VS Code version.
- Extension version. 
- Concrete clipboard contents.
- Concrete line contents where this happens during paste.
- Any other extra steps/info that might help.

Thanks!

**Comment by yaagma** [comment] 2020-11-04 08:23
I found it!!

Steps I followed:
- I installed a clean portable versión of VSC and installed only your extension. Everything worked Ok.
- I copied my old `settings.json` (I had about 380 settings). The bug appeared again.
- I deleted sections of settings until I found the problem:
> "editor.formatOnPaste": true

If I change it to `false`, the bug goes away.

In summary, the steps to reproduce the error are:
1. Introduce in the clipboard any text (for example, "123").
1. Set "editor.formatOnPaste" to `true`.
1. Create an empty `md` file,
1. Type anything in the first line (for example "abc").
1. Paste (`Ctrl + v`). Instead of "abc123", you get "abcabc123" (repeats de line content before pasting).

I hope this helps.

OS platform. Windows 10
VS Code version. Tested in 1.46.1 and 1.50.1
Extension version. v3.0.0
Concrete clipboard contents. 123
Concrete line contents where this happens during paste. a \n \b \n
Any other extra steps/info that might help.

**Comment by darkriszty** [comment] 2020-11-04 10:17
Thanks, this has been a huge help! I will include a fix in the next release.

**Comment by darkriszty** [comment] 2020-11-04 16:27
Thanks again to both of you for reporting! The fix is included in v3.1.0; it should show up as an extension update in VSCode.

**Closed by darkriszty** 2020-11-04 16:27 UTC
Labels: bug

**Comment by danmactough** [comment] 2020-11-04 18:38
Confirmed working @darkriszty! Thanks for the quick fix! 💖
